name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  container:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        container:
          - caddy
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: containers/${{ matrix.container }}
          file: containers/${{ matrix.container }}/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  oci-artifacts:
    name: OCI artifact
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - caddy
          - postgres
          - redis
          - smtp
          - web
    steps:
      - uses: actions/checkout@v6
      - uses: codingjoe/the-box/actions/compose@main
        with:
          version: 1.29.2
      - run: docker compose --file containers/compose.${{ matrix.service }}.yml config --no-interpolate --no-path-resolution --no-env-resolution -o compose.${{ matrix.service }}.compiled.yml
      - run: docker stack config -c compose.${{ matrix.service }}.compiled.yml
      - run: docker compose --file compose.${{ matrix.service }}.compiled.yml publish  --yes --dry-run ${{ github.actor }}/the-box-${{ matrix.service }}
      - uses: actions/upload-artifact@v6
        with:
          name: compose.${{ matrix.service }}.yml
          path: compose.${{ matrix.service }}.compiled.yml
