name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  container:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        container-file:
          - containers/web/node/Dockerfile
          - containers/web/python/Dockerfile
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.container-file }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  compose:
    name: compose
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compose-file:
          - compose.yml
          - compose.app.yml
          - containers/compose.caddy.yml
          - containers/compose.postgres.yml
          - containers/compose.redis.yml
          - containers/compose.smtp.yml
          - containers/compose.web.yml

    steps:
      - uses: actions/checkout@v6
      - run: docker compose --file ${{ matrix.compose-file }} config --no-interpolate --no-path-resolution --no-env-resolution --quiet
