name: Deploy
on:
  workflow_call:
    inputs:
      SSH_HOSTNAME:
        required: false
        type: string
      SSH_KNOWN_HOSTS:
        required: false
        type: string
      HOSTNAME:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      DOTENV_PRIVATE_KEY_PRODUCTION:
        required: true
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  paas:
    if: inputs.SSH_HOSTNAME != ''
    name: PaaS
    runs-on: ubuntu-latest
    concurrency: production
    steps:
      - uses: actions/checkout@v6
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pin known hosts
        run: |
          echo "::group::Pinning known hosts"
          echo "${{ inputs.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "::debug::Known hosts updated:"
          cat ~/.ssh/known_hosts
          echo "::endgroup::"
      - name: Setting up Docker context for remote deployment
        run: |
          docker context create production --description "Production Server" --docker "host=ssh://github@${{ inputs.SSH_HOSTNAME }}"
          docker context use production
      - name: Deploy production containers
        run: docker compose --file compose.paas.yml --project-name paas up --detach --quiet-pull
        env:
          HOSTNAME: ${{ inputs.HOSTNAME }}
  app:
    if: inputs.SSH_HOSTNAME != ''
    needs: paas
    name: App
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ inputs.HOSTNAME }}/
    concurrency: production
    steps:
      - uses: actions/checkout@v6
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pin known hosts
        run: |
          echo "::group::Pinning known hosts"
          echo "${{ inputs.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "::debug::Known hosts updated:"
          cat ~/.ssh/known_hosts
          echo "::endgroup::"
      - name: Setting up Docker context for remote deployment
        run: |
          docker context create production --description "Production Server" --docker "host=ssh://github@${{ inputs.SSH_HOSTNAME }}"
          docker context use production
          touch .env
      - name: Deploy production containers
        run: docker compose --file compose.app.yml --project-name app up --detach --quiet-pull
        env:
          HOSTNAME: ${{ inputs.HOSTNAME }}
          DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
